name: expense_repository
description: The Repo that handles expense
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  # rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true